name: Docker Image CI

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  USERNAME: ${{ github.actor }}
  REPOSITORY: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Version TAG
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Test
      run: |
        echo $USERNAME
        echo $REPOSITORY
        echo $RELEASE_VERSION
        echo $USERNAME/$REPOSITORY:$RELEASE_VERSION
